### ISSUE TITLE
点击解析视频报下面这个错误

### ISSUE THREAD

**Issue by doasdsadsaf** [Johnserf-Seed/TikTokWeb#11]
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by Johnserf-Seed** [comment]
目前是官方接口寄了
