### ISSUE TITLE
项目是不维护了吧？

### ISSUE THREAD

**Issue by soom-lupulus** [Johnserf-Seed/TikTokWeb#13]
我看里面的CDN都失效了，也没有在处理，不改下这项目是用不了了

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/218244474-1c7bbb52-d6eb-4061-8260-e43a9f9bf92c.png)
能用阿，自己检查一下本地是不是最新吧
