### ISSUE TITLE
填写了cookie仍然解析报错

### ISSUE THREAD

**Issue by guytakeiteasy** [Johnserf-Seed/TikTokWeb#36]
如题，一开始在docker中部署可以正常解析，使用了大概2天后就不行了，解析时提示：抖音的cooki无效，请重新填写
但是我并没有改变任何东西，是什么原因呢？

**Comment by Johnserf-Seed** [comment]
这个cookie使用太多次被风控了，因为web版的cookie是一直会刷新状态的，只需要打开网页版抖音重新获取cookie即可。

**Comment by guytakeiteasy** [comment]
> 这个cookie使用太多次被风控了，因为web版的cookie是一直会刷新状态的，只需要打开网页版抖音重新获取cookie即可。
原来是这样，谢谢大佬指点！
