### ISSUE TITLE
解析出来非1080p 分辨率很低

### ISSUE THREAD

**Issue by donqee** [Johnserf-Seed/TikTokWeb#4]
解析出来非1080p 分辨率很低，希望可以有选项选择高清

**Comment by donqee** [comment]
还不能实现1080p

**Comment by Johnserf-Seed** [comment]
请看readme

**Comment by iblogc** [comment]
分辨率好像还不是1080的，是1024*576，并且短链接是不能解析（用README里的短链接https://v.douyin.com/NKyY6Ch/ 解析也是404）
